### ISSUE TITLE
1 step in the readme is redundant

### ISSUE THREAD

**Issue by steveok67** [openshift/compliance-operator#128]
Question: When executing the steps below:

$ (clone repo)
$ oc create -f deploy/ns.yaml
$ for f in $(ls -1 deploy/crds/*crd.yaml); do oc create -f $f; done
$ oc create -f deploy/

$ oc create -f deploy/ns.yaml, is run after cloning, then it's run again when we run: oc create -f deploy/

Is: $ oc create -f deploy/ns.yaml still necessary?

**Comment by jhrozek** [comment]
Yes, it is still necessary. Some objects in the manifests under `deploy` are namespaced and must exist in the `openshift-compliance` namespace. And if the namespace didn't exist prior to attempting to create these objects, creating these objects might fail. So the safe thing to do is to create the namespace first.

Thank you for filing the issue. Do you think it is OK to close it now?

**Comment by steveok67** [comment]
Yes - we can close it.  Thanks.
