### ISSUE TITLE
OpenSCAP Error: Document is empty

### ISSUE THREAD

**Issue by trevor-viljoen** [openshift/compliance-operator#195]
I'm unable to get the compliancesuite CR to complete. `oc get compliancesuites test-compliancesuite -o yaml` shows: 

```
scanStatuses:
- errormsg: |
    OpenSCAP Error: Document is empty [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:305]
    Is a directoryEntity: line 1: parser error: Document is empty
    ^
    Unable to parse XML at: '/content' [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:307]
  name: workers-scan
  phase: DONE
  result: ERROR
- errormsg: |
    OpenSCAP Error: Document is empty [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:305]
    Is a directoryEntity: line 1: parser error: Document is empty
    ^
    Unable to parse XML at: '/content' [/builddir/build/BUILD/openscap-1.3.1/src/source/oscap_source.c:307]
  name: masters-scan
  phase: DONE
  result: ERROR
```

The `contentImage` is `quay.io/jhrozek/ocp4-openscap-content:latest`.
The `profile` is `xccdf_org.ssgproject.content_profile_coreos-ncp`.

The only change to the CR from the openshift/compliance-operator repo was to change `autoApplyRemediations` to false.

**Comment by shawndwells** [comment]
@jhrozek ps, https://github.com/openshift/compliance-operator/blob/master/deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml#L11 still points to the initial/alpha repo. 

Could/should it be referencing the ComplianceAsCode repo we made during the Brno trip?

**Comment by trevor-viljoen** [comment]
It looks like maybe this is the right Dockerfile: https://github.com/ComplianceAsCode/content/blob/master/Dockerfiles/ocp4_content

Is this image pushed in Quay anywhere?

**Comment by shawndwells** [comment]
@trevor-viljoen Yes. We fixed that a few months back via https://github.com/ComplianceAsCode/content/pull/5135.

But looking at https://quay.io/organization/ComplianceAsCode the repo/images are missing.

Looks like things are quietly being staged in https://quay.io/repository/slukasik/complianceascode through automated builds. So if something is needed *now* feel free to poke there.

Paging @isimluk to clarify though.

**Comment by jhrozek** [comment]
We really haven't implemented an official way to push the content images. But you're right that the example CR has some issues, first, as you said, the example CR shouldn't auto apply remediations. Second, the fedramp moderate profile is no longer called `xccdf_org.ssgproject.content_profile_coreos-ncp` but `xccdf_org.ssgproject.content_profile_moderate`. That said, even the ncp profile should work, it is just not up to date. I'll open a PR fixing those two issues.

As per why the content is empty, I'm not sure, everything works fine for me locally, and the operator has an e2e test suite that should catch glaring issues like these. Would you mind pasting the operator logs? It almost sounds like there's an issue with the init container that copies the content for use by the scanner.

**Comment by jhrozek** [comment]
Oh, and I regenerated the content image with what's in CaC master branch now.

**Comment by trevor-viljoen** [comment]
Using the updated example CR, I was able to generate scans. I will apply the same setup to our lab environment to verify, but I believe we can close this out.

**Comment by jhrozek** [comment]
Since there was no more activity on this issue in ~2 weeks, I'm going to close it. Please reopen if the issue persists.

**Comment by JAORMX** [comment]
@vivekyoganand the name `ocp4-cis-node` looks suspicious to me. Can you share the YAML files you used to create this?

**Comment by CristianAGR** [comment]
Hi, i just installed openscap and scap-security-guide on AlmaLinux 9, but i am receiving this error when i try to execute any oscap command, for example here i am trying to list the profiles availabe, any idea why can be happening?
![imagen_2024-08-28_000353226](https://github.com/user-attachments/assets/28584eb9-2cce-4f28-a6d0-2372a91ba0db)
