### ISSUE TITLE
Change default contentImage to ComplianceAsCode upstream?

### ISSUE THREAD

**Issue by shawndwells** [openshift/compliance-operator#216]
In ``deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml`` the default contentImage points to ``quay.io/jhrozek/ocp4-openscap-content:latest``

Believe https://quay.io/organization/complianceascode was created and @isimluk wrote some automation to have the image updated with every PR. 

Would it be OK to submit a PR to change the default contentImage to the upstream?

**Comment by isimluk** [comment]
We have https://quay.io/repository/slukasik/complianceascode that builds with each commit in ComplianceAsCode. I would love to move this under https://quay.io/organization/complianceascode . Can You please give me rights to do so?
