### ISSUE TITLE
how to watch scan progress?

### ISSUE THREAD

**Issue by shawndwells** [openshift/compliance-operator#217]
In the README it says to issue the following command to watch progress:

``$ oc get compliancesuites/$suite-name -oyaml``

From ``deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml`` it appears this is from the metadata name, ``example-compliancesuite``:
`````
$ cat deploy/crds/compliance.openshift.io_v1alpha1_compliancesuite_cr.yaml
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: example-compliancesuite
`````

However, the following command fails:
`````
$ oc get compliancesuites/example-compliancesuite
Error from server (NotFound): compliancesuites.compliance.openshift.io "example-compliancesuite" not found

`````

**Comment by JAORMX** [comment]
you can get all the compliancesuites in the system with
```
oc get compliancesuites
```
if you want to watch for changes, add the `-w` flag. e.g.:
```
oc get compliancesuites -w
```
To see how a specific compliancesuite (that was created earlier) is doing and all the data the yaml file has, then the `-o yaml` flag is useful, which is what you were trying.
