### ISSUE TITLE
Installs into default project namespace

### ISSUE THREAD

**Issue by shawndwells** [openshift/compliance-operator#218]
Docs need to be updated to ``oc project`` into the compliance operator namespace after creating it.

Or the CRDs can be updated to use the ``openshift-compliance`` namespace. Looks like only the compliance remediation one does that now:

$ grep -rin namespace
compliance.openshift.io_compliancesuites_crd.yaml:19:  scope: Namespaced
compliance.openshift.io_compliancecheckresults_crd.yaml:19:  scope: Namespaced
compliance.openshift.io_v1alpha1_complianceremediation_cr.yaml:13:  namespace: openshift-compliance
compliance.openshift.io_complianceremediations_crd.yaml:16:  scope: Namespaced
compliance.openshift.io_compliancescans_crd.yaml:19:  scope: Namespaced

**Comment by npoyant** [comment]
https://github.com/openshift/compliance-operator/pull/219

**Comment by jhrozek** [comment]
I'm going to also close this issue since it was addressed by PR#219.
