### ISSUE TITLE
Need a cleanup tool/script to remove everything

### ISSUE THREAD

**Issue by npoyant** [openshift/compliance-operator#229]

**Comment by JAORMX** [comment]
Could you specify what you want to get removed? The deployment itself or the custom resources?

**Comment by npoyant** [comment]
Previously this was requested <=4.3 versions of the deployment where everything was still a manual process.  I see that it has been converted to an operator in >=4.4 versions.  I have not been able to test the compliance operator in a couple of months but assuming the operator can be uninstalled then that would make this issue a moot point.
