### ISSUE TITLE
Get nist-rhcos-scan has no role

### ISSUE THREAD

**Issue by cynthia-rempel** [openshift/compliance-operator#291]
Hi,

How's it going?

I'm trying to get a SCAP scan of both the application (Openshift 4) and the OS (CoreOS), and I'm running into this error:

 oc logs aggregator-pod-nist-rhcos-scan

Creating :nist-rhcos-scan-account-disable-post-pw-expiration
Creating :nist-rhcos-scan-accounts-no-uid-except-zero
Creating :nist-rhcos-scan-audit-rules-dac-modification-chmod
Could not create remediation objects: scan nist-rhcos-scan has no role assignment

This is my:
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceSuite
metadata:
  name: coreos-compliancesuite
spec:
  autoApplyRemediations: false
  schedule: "55 * * * *"
  scans:
    - name: workers-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_opencis-node
      content: ssg-ocp4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      # rule: "xccdf_org.ssgproject.content_rule_no_netrc_files"
      # nodeSelector:
      #  node-role.kubernetes.io/worker: ""
    - name: masters-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_opencis-master
      content: ssg-ocp4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      # rule: "xccdf_org.ssgproject.content_rule_no_netrc_files"
      nodeSelector:
        node-role.kubernetes.io/master: ""
    - name: nist-rhcos-scan
      scanType: Node
      profile: xccdf_org.ssgproject.content_profile_moderate
      content: ssg-rhcos4-ds.xml
      contentImage: quay.io/complianceascode/ocp4:latest
      # rule: "xccdf_org.ssgproject.content_rule_no_netrc_files"
      # nodeSelector:
      #  node-role.kubernetes.io/master: ""

**Comment by JAORMX** [comment]
We're working on fixing that issue.

Currently, the only way for the compliance-operator to generate remediations is if the nodeSelector you use matches a MachineConfigPool object (we need to document this better). This way, it'll create a MachineConfigs that apply to that certain pool.

You would need to uncomment the `nodeSelector` sections from the scans in the compliancesuite

**Comment by cynthia-rempel** [comment]
Thanks! I really appreciate the help :)
