### ISSUE TITLE
Leader Pod crashing 

### ISSUE THREAD

**Issue by groenator** [openshift/compliance-operator#360]
I deployed the operator in my OKD cluster, followed the guide creating the scans. 

However, the leader pod (if I understood correctly) is crashing.

Any idea why is this happening?

```{"level":"info","ts":1594133199.468049,"logger":"scanctrl","msg":"Content image","Request.Namespace":"openshift-compliance","Request.Name":"workers-scan","image":"quay.io/complianceascode/ocp4:latest"}
{"level":"info","ts":1594133199.4718995,"logger":"scanctrl","msg":"deleting server cert","Request.Namespace":"openshift-compliance","Request.Name":"workers-scan","ComplianceScan.Name":"workers-scan"}
{"level":"info","ts":1594133199.4761467,"logger":"scanctrl","msg":"deleting client cert","Request.Namespace":"openshift-compliance","Request.Name":"workers-scan","ComplianceScan.Name":"workers-scan"}
{"level":"info","ts":1594133199.4800355,"logger":"scanctrl","msg":"deleting CA","Request.Namespace":"openshift-compliance","Request.Name":"workers-scan","ComplianceScan.Name":"workers-scan"}
E0707 14:46:39.491434       1 runtime.go:78] Observed a panic: &errors.errorString{s:"cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'"} (cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$')
goroutine 3748 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x21d6040, 0xc0007bc500)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xc4
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0xbe
panic(0x21d6040, 0xc0007bc500)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:127 +0x23d
github.com/openshift/compliance-operator/pkg/controller/compliancescan.getPVCForScan(0xc0008a0900, 0x0)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/rawresults.go:80 +0x1a3
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).deleteRawResultsForScan(0xc00066a8a0, 0xc0008a0900, 0x2753160, 0xc0005a0f20)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/rawresults.go:50 +0x40
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).scanDeleteHandler(0xc00066a8a0, 0xc000806b40, 0x2753160, 0xc0005a0f20, 0x14, 0xc000e14b44, 0xc, 0x270d060)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/compliancescan_controller.go:522 +0x23e
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).Reconcile(0xc00066a8a0, 0xc0017fb460, 0x14, 0xc000e14b44, 0xc, 0x17bc031, 0xc001119cd8, 0xc0005f6180, 0xc0009c1c98)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/compliancescan_controller.go:129 +0xd1e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001e20c0, 0x2268680, 0xc0005a0d00, 0xc000de2f00)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x1d0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001e20c0, 0x35cee00)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0x11e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001e20c0)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x39
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000e18250)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e18250, 0x26ff6e0, 0xc0006f1230, 0xc000a62201, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb4
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e18250, 0x3b9aca00, 0x0, 0x1, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x146
k8s.io/apimachinery/pkg/util/wait.Until(0xc000e18250, 0x3b9aca00, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x5b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x4fb
panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$' [recovered]
	panic: cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'

goroutine 3748 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x169
panic(0x21d6040, 0xc0007bc500)
	/usr/lib/golang/src/runtime/panic.go:679 +0x1b2
k8s.io/apimachinery/pkg/api/resource.MustParse(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/api/resource/quantity.go:127 +0x23d
github.com/openshift/compliance-operator/pkg/controller/compliancescan.getPVCForScan(0xc0008a0900, 0x0)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/rawresults.go:80 +0x1a3
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).deleteRawResultsForScan(0xc00066a8a0, 0xc0008a0900, 0x2753160, 0xc0005a0f20)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/rawresults.go:50 +0x40
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).scanDeleteHandler(0xc00066a8a0, 0xc000806b40, 0x2753160, 0xc0005a0f20, 0x14, 0xc000e14b44, 0xc, 0x270d060)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/compliancescan_controller.go:522 +0x23e
github.com/openshift/compliance-operator/pkg/controller/compliancescan.(*ReconcileComplianceScan).Reconcile(0xc00066a8a0, 0xc0017fb460, 0x14, 0xc000e14b44, 0xc, 0x17bc031, 0xc001119cd8, 0xc0005f6180, 0xc0009c1c98)
	/go/src/github.com/openshift/compliance-operator/pkg/controller/compliancescan/compliancescan_controller.go:129 +0xd1e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001e20c0, 0x2268680, 0xc0005a0d00, 0xc000de2f00)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x1d0
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001e20c0, 0x35cee00)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0x11e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc0001e20c0)
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x39
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000e18250)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x70
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000e18250, 0x26ff6e0, 0xc0006f1230, 0xc000a62201, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb4
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000e18250, 0x3b9aca00, 0x0, 0x1, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x146
k8s.io/apimachinery/pkg/util/wait.Until(0xc000e18250, 0x3b9aca00, 0xc00001e0c0)
	/go/src/github.com/openshift/compliance-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x5b
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
	/go/src/github.com/openshift/compliance-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x4fb```

Regards,

**Comment by JAORMX** [comment]
What OKD and kube version is this?

**Comment by groenator** [comment]
Hi @JAORMX 

The version of OKD that I am running is this;

```
oc version
Client Version: 4.3.18
Server Version: 4.4.0-0.okd-2020-07-10-000426
Kubernetes Version: v1.17.1
```

I can confirm that I installed the operator on OCP 4 without any issues. 

Thank you!

**Comment by JAORMX** [comment]
@groenator thanks for getting back on this!

How did you deploy? did you use the master branch? What's the manifest you used for creating the compliance suite or scan?

After creating the suite or scan, could you get it again using `oc get ....` this would be to verify that the appropriate default was set (seems to me it wasn't). Defaulting values from the kube-apiserver should work from 1.17, which is what you're using.

**Comment by tmishina** [comment]
@JAORMX
I faced same issue (`cannot parse '': quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'`) on a IBM Cloud OpenShift cluster with default deployment (I followed the instruction in README.md) while older commit (e.g., `eb91236`) worked well.

According to your comment, this may be caused by the older version of kube.
```
 $ oc version
Client Version: openshift-clients-4.3.19-202005020952
Server Version: 4.3.23
Kubernetes Version: v1.16.2+18cfcc9
```
Is there workaround to the issue? (e.g., modify XXX.go and `make run` instead of applying `deploy/operator.yaml`)

**Comment by JAORMX** [comment]
@jhrozek @mrogers950 could you check this out?

**Comment by JAORMX** [comment]
@tmishina @groenator as a workaround, could you add the `rawResultStorage.size` parameter? It would look similar to this:

```
apiVersion: compliance.openshift.io/v1alpha1
kind: ComplianceScan
metadata:
  name: worker-scan
spec:
  scanType: Node
  profile: xccdf_org.ssgproject.content_profile_moderate
  content: ssg-ocp4-ds.xml
  contentImage: quay.io/complianceascode/ocp4:latest
  rule: "xccdf_org.ssgproject.content_rule_no_netrc_files"
  nodeSelector:
    node-role.kubernetes.io/worker: ""
  rawResultStorage:
    size: '1Gi'
```

**Comment by groenator** [comment]
Thanks @JAORMX I will add this parameter.

**Comment by jhrozek** [comment]
Since commit 10fd4d7f901f65645fed3053b4616d6db4c5304a we should be setting the default size even if unspecified explicitly. Can you paste the output of `oc get deployments/compliance-operator -nopenshift-compliance -oyaml` to see what version are you running?

**Comment by tmishina** [comment]
＠JAORMX

Thank you! I tried to apply your example `ComplianceScan` resource, but the behavior of the operator did not change.
I confirmed that `rawResultStorage:` parameter is removed when `Reconcile` of ComplianceSuite once runs.

I then tried an ad-hoc solution to perform `make run`.
modify:
https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/pkg/controller/compliancescan/compliancescan_controller.go#L169
to:
```go
	if instanceCopy.Spec.RawResultStorage.Size != compv1alpha1.DefaultRawStorageSize {
```

and change this 
https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/cmd/manager/resultserver.go#L150
to:
```go
				CreationTime: timespecToTime(statinfo.Ctimespec),
```
(I don't know why this change is required; because I'm using macOS Mojave?)

Then, worker started to work well. 
However, compliancescan returns error as below.

```
 $ k describe compliancescan workers-scan
Name:         workers-scan
Namespace:    openshift-compliance
...
Spec:
  Content:        ssg-ocp4-ds.xml
  Content Image:  quay.io/complianceascode/ocp4:latest
  Node Selector:
    node-role.kubernetes.io/worker:
  Profile:                           xccdf_org.ssgproject.content_profile_moderate
  Raw Result Storage:
    Rotation:  3
    Size:      1Gi
  Scan Tolerations:
    Effect:    NoSchedule
    Key:       node-role.kubernetes.io/master
    Operator:  Exists
Status:
  Errormsg:  OpenSCAP Error: File '/content/ssg-ocp4-ds.xml' line 3871: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_test': This element is not expected.
 [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
File '/content/ssg-ocp4-ds.xml' line 5114: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_object': This element is not expected.
 [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
...(a number of similar lines continue)
```

Is this causedy by compliance operator? or ComplianceAsCode image? (`quay.io/complianceascode/ocp4:latest`)

**Comment by JAORMX** [comment]
> ＠JAORMX
> 
> Thank you! I tried to apply your example `ComplianceScan` resource, but the behavior of the operator did not change.
> I confirmed that `rawResultStorage:` parameter is removed when `Reconcile` of ComplianceSuite once runs.
> 
> I then tried an ad-hoc solution to perform `make run`.
> modify:
> 
> https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/pkg/controller/compliancescan/compliancescan_controller.go#L169
> 
> to:
> 
> ```go
> 	if instanceCopy.Spec.RawResultStorage.Size != compv1alpha1.DefaultRawStorageSize {
> ```
> 
> and change this
> 
> https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/cmd/manager/resultserver.go#L150
> 
> to:
> 
> ```go
> 				CreationTime: timespecToTime(statinfo.Ctimespec),
> ```
> 
> (I don't know why this change is required; because I'm using macOS Mojave?)
> 

Might be, we usually test this on Linux.

> Then, worker started to work well.
> However, compliancescan returns error as below.
> 
> ```
>  $ k describe compliancescan workers-scan
> Name:         workers-scan
> Namespace:    openshift-compliance
> ...
> Spec:
>   Content:        ssg-ocp4-ds.xml
>   Content Image:  quay.io/complianceascode/ocp4:latest
>   Node Selector:
>     node-role.kubernetes.io/worker:
>   Profile:                           xccdf_org.ssgproject.content_profile_moderate
>   Raw Result Storage:
>     Rotation:  3
>     Size:      1Gi
>   Scan Tolerations:
>     Effect:    NoSchedule
>     Key:       node-role.kubernetes.io/master
>     Operator:  Exists
> Status:
>   Errormsg:  OpenSCAP Error: File '/content/ssg-ocp4-ds.xml' line 3871: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_test': This element is not expected.
>  [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
> File '/content/ssg-ocp4-ds.xml' line 5114: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_object': This element is not expected.
>  [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
> ...(a number of similar lines continue)
> ```
> 
> Is this causedy by compliance operator? or ComplianceAsCode image? (`quay.io/complianceascode/ocp4:latest`)

That sounds like it's an issue with the openscap image that's being used. @jhrozek @mrogers950 wouldn't the default image of openscap already have support for the yaml checks?

@tmishina on the other hand, what type of scan do you wanna do? do you wanna do OCP checks? or do you wanna do RHCOS checks?

There might be different parameters you need to add depending on the case. We have some enhancements to make this flow more user-friendly by creating default profiles that are ready to use and accessible through the operator. you can see them if you do:

```
oc get profiles.compliance
```

@jhrozek @mrogers950 when you add docs for the ScanSettings and ScanSettingBindings could you link the PR to this? so @tmishina could take them into use. That would make things simpler when crafting suite run policies.

**Comment by tmishina** [comment]
@JAORMX I'd like to perform CIS check for OCP4 on IBM Cloud OpenShift clusters (ROKS). ROKS is an OCP 4.3 cluster running on RHEL 7. 
I'd appreciate it if I can use `oc get profiles.compliance` to specify the profile.

```
 $ oc -n openshift-compliance get profiles.compliance
NAME              AGE
ocp4-cis          25h
ocp4-e8           25h
ocp4-moderate     25h
ocp4-ncp          25h
rhcos4-e8         25h
rhcos4-moderate   25h
rhcos4-ncp        25h
```

sorry for changing the context; please guide me if there is better location to discuss this topic.

**Comment by jhrozek** [comment]
Ugh, I edited the original post when I wanted to reply inline...let me at least unqote my reply...

> > ＠JAORMX
> > Thank you! I tried to apply your example `ComplianceScan` resource, but the behavior of the operator did not change.
> > I confirmed that `rawResultStorage:` parameter is removed when `Reconcile` of ComplianceSuite once runs.
> > I then tried an ad-hoc solution to perform `make run`.
> > modify:
> > https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/pkg/controller/compliancescan/compliancescan_controller.go#L169
> > 
> > to:
> > ```go
> > 	if instanceCopy.Spec.RawResultStorage.Size != compv1alpha1.DefaultRawStorageSize {
> > ```
> > 
> > 
> > and change this
> > https://github.com/openshift/compliance-operator/blob/d9ff1f7fc9d063f36bd12e2bc66dc9e4a53360ec/cmd/manager/resultserver.go#L150
> > 
> > to:
> > ```go
> > 				CreationTime: timespecToTime(statinfo.Ctimespec),
> > ```
> > 
> > 
> > (I don't know why this change is required; because I'm using macOS Mojave?)
> 
> Might be, we usually test this on Linux.
> 
> > Then, worker started to work well.
> > However, compliancescan returns error as below.
> > ```
> >  $ k describe compliancescan workers-scan
> > Name:         workers-scan
> > Namespace:    openshift-compliance
> > ...
> > Spec:
> >   Content:        ssg-ocp4-ds.xml
> >   Content Image:  quay.io/complianceascode/ocp4:latest
> >   Node Selector:
> >     node-role.kubernetes.io/worker:
> >   Profile:                           xccdf_org.ssgproject.content_profile_moderate
> >   Raw Result Storage:
> >     Rotation:  3
> >     Size:      1Gi
> >   Scan Tolerations:
> >     Effect:    NoSchedule
> >     Key:       node-role.kubernetes.io/master
> >     Operator:  Exists
> > Status:
> >   Errormsg:  OpenSCAP Error: File '/content/ssg-ocp4-ds.xml' line 3871: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_test': This element is not expected.
> >  [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
> > File '/content/ssg-ocp4-ds.xml' line 5114: Element '{http://oval.mitre.org/XMLSchema/oval-definitions-5#independent}yamlfilecontent_object': This element is not expected.
> >  [/builddir/build/BUILD/openscap-1.3.3/src/XCCDF/xccdf_session.c:613]
> > ...(a number of similar lines continue)
> > ```
> > 
> > 
> > Is this causedy by compliance operator? or ComplianceAsCode image? (`quay.io/complianceascode/ocp4:latest`)
> 
> That sounds like it's an issue with the openscap image that's being used. @jhrozek @mrogers950 wouldn't the default image of openscap already have support for the yaml checks?
> 

Yes, this sounds like the old openscap image is being used. That's why I asked for the deployment details earlier :-)

> 
> @tmishina on the other hand, what type of scan do you wanna do? do you wanna do OCP checks? or do you wanna do RHCOS checks?
> 
> There might be different parameters you need to add depending on the case. We have some enhancements to make this flow more user-friendly by creating default profiles that are ready to use and accessible through the operator. you can see them if you do:
> 
> ```
> oc get profiles.compliance
> ```
> 
> @jhrozek @mrogers950 when you add docs for the ScanSettings and ScanSettingBindings could you link the PR to this? so @tmishina could take them into use. That would make things simpler when crafting suite run policies.
> 

Sure, I've been asked to fixup the docs by our QE team anyway.

**Comment by mrogers950** [comment]
@tmishina you might have ended up with the wrong OPENSCAP_IMAGE image if you deployed using the dev workflow (i.e., make image-to-cluster) while some things were in flux. Please try using `deploy/olm-catalog/operator-source.yaml` to install from the catalog, and you'll be on our newest release images.

However the CIS profile currently does not work for us, at least under CoreOS. We will need the checks to be updated to platform type and/or MC remediations. If you try it on CoreOS right now the checks return as Not Applicable. It might be worth a shot running it on RHEL7 workers to see what happens, but we have not tested it. I ran it like this:
```
spec:
  scanType: Node
  content: ssg-ocp4-ds.xml
  contentImage: quay.io/complianceascode/ocp4:latest
  profile: xccdf_org.ssgproject.content_profile_cis
```

Only difference with what you were doing before is specifying the "cis" instead of "moderate" profile.

**Comment by tmishina** [comment]
@JAORMX @jhrozek @mrogers950 
Thank you very much for your comments, I finally succeeded to perform compliance scan.

To use the latest OPENSCAP_IMAGE, I first tried to install the operator by OperatorHub.

```
 $ oc -n openshift-marketplace  apply -f deploy/olm-catalog/operator-source.yaml
operatorsource.operators.coreos.com/compliance-operator created
```

However, `compliance-operator` was not listed in OperatorHub UI, (probably) due to the following error.

```
 $ oc logs -n openshift-marketplace compliance-operator-5f6f9456fc-xb9gk
...
...
time="2020-07-15T02:18:22Z" level=warning msg="strict mode disabled" error="error loading manifests from appregistry: error loading operator manifests: [error checking provided apis in bundle : error decoding CRD: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/registry/bundle.go:15\", error adding operator bundle : error decoding CRD: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/registry/bundle.go:15\", error loading package into db: [FOREIGN KEY constraint failed, no default channel specified for compliance-operator-bundle]]" port=50051 type=appregistry
```

I changed my strategy to use `make run` again.

Change here:
https://github.com/openshift/compliance-operator/blob/d904e29a148d6d2c894a0a4f92c780055b279850/pkg/utils/images.go#L17
to:

```go
	{"quay.io/compliance-operator/openscap-ocp:scratch_63799-20200709162434", "OPENSCAP_IMAGE"},
```
(tag name came from https://quay.io/repository/compliance-operator/openscap-ocp?tab=tags)

In addition, change here:
https://github.com/openshift/compliance-operator/blob/d904e29a148d6d2c894a0a4f92c780055b279850/pkg/controller/compliancescan/rawresults.go#L80

to:
```go
					corev1.ResourceStorage: resource.MustParse("1Gi"),
```

to avoid the default value issue.
Then, finally, the worker pod successfully started.


```
 $ k get pod workers-scan-10.221.139.104-pod -o yaml
apiVersion: v1
kind: Pod
metadata:
  ...
  name: workers-scan-10.221.139.104-pod
  namespace: openshift-compliance
  ...
spec:
  containers:
  ...
  - command:
    - /scripts/openscap-container-entrypoint
    envFrom:
    - configMapRef:
        name: workers-scan-openscap-env-map
    image: quay.io/compliance-operator/openscap-ocp:scratch_63799-20200709162434
    imagePullPolicy: IfNotPresent
    name: openscap-ocp
    ...
```
```
 $ k get compliancescan workers-scan
NAME           PHASE   RESULT
workers-scan   DONE    NOT-APPLICABLE
(compl-op-auditree) tmishina@tmishina-mbp18:~/workspace/auditree-evolve/compliance-operator
 $ k get compliancesuite
NAME                      PHASE   RESULT
example-compliancesuite   DONE    NOT-APPLICABLE
```
(hope I could get result rather than `NOT-APPLICABLE`, but it's a [separate issue](https://github.com/openshift/compliance-operator/issues/292)...)

I believe these ad-hoc modifications will be no longer required when the default value for `rawResultStorage.size` is set as mentioned in the [comment](https://github.com/openshift/compliance-operator/issues/360#issuecomment-657614159).
(`OPENSCAP_IMAGE` can be specified in `operator.yaml` when the image `quay.io/compliance-operator/compliance-operator:latest` is updated)

Thanks again!

**Comment by jhrozek** [comment]
This issue about loading manifests:
```
time="2020-07-15T02:18:22Z" level=warning msg="strict mode disabled" error="error loading manifests from appregistry: error loading operator manifests: [error checking provided apis in bundle : error decoding CRD: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/registry/bundle.go:15\", error adding operator bundle : error decoding CRD: no kind \"CustomResourceDefinition\" is registered for version \"apiextensions.k8s.io/v1\" in scheme \"pkg/registry/bundle.go:15\", error loading package into db: [FOREIGN KEY constraint failed, no default channel specified for compliance-operator-bundle]]" port=50051 type=appregistry
```
/might/ be expected with older k8s/OCP clusters as the `v1` version of the `apiextensions.k8s.io` API group is only present in recent OCP clusters. We've really been focused on 4.6+ in our development as that's where the operator would ship. I'd like to install and older (4.4 as this error had been reported in another ticket as well with 4.4..) cluster to verify at least.

**Comment by tmishina** [comment]
@jhrozek My test bed is OCP4.3 on RHEL7, so it would be too old than what you expected...but `CustomResourceDefinition` exists in `apiextensions.k8s.io/v1`. I'm wondering why this error occurred.

```
 $ kubectl explain crd
KIND:     CustomResourceDefinition
VERSION:  apiextensions.k8s.io/v1

DESCRIPTION:
     CustomResourceDefinition represents a resource that should be exposed on
     the API server. Its name MUST be in the format <.spec.name>.<.spec.group>.

FIELDS:
   apiVersion	<string>
     APIVersion defines the versioned schema of this representation of an
     object. Servers should convert recognized schemas to the latest internal
     value, and may reject unrecognized values. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources

   kind	<string>
     Kind is a string value representing the REST resource this object
     represents. Servers may infer this from the endpoint the client submits
     requests to. Cannot be updated. In CamelCase. More info:
     https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds

   metadata	<Object>

   spec	<Object> -required-
     spec describes how the user wants the resources to appear

   status	<Object>
     status indicates the actual state of the CustomResourceDefinition
```
