### ISSUE TITLE
Need way to instruct operator to publish scan reports 

### ISSUE THREAD

**Issue by rflorenc** [openshift/compliance-operator#468]
Would be very useful to have a way to automatically publish the generated oscap reports after a scan is finished, in a given cluster, either via annotation to the operator or compliancesuite's spec, for example: `publish-report: True`.  

Tool written in Go here:
https://github.com/rflorenc/ocp4-compliance-reportgen

Following up on the work by @kharyam here:
https://github.com/kharyam/compliance-operator-demo

**Comment by JAORMX** [comment]
We have gotten several requests about this feature, and it would sure be nice to have!

A couple of questions (gathering requirements):

* Besides report-viewing, what other actions would you do if you had a UI for the operator?
* Who should have access to look at such reports?
* Is there extra information in the report you generated that would be beneficial to have?

**Comment by emergency6300** [comment]
It would ne nice to be able to offer users direct access to the security reporting data directly through a website. 
Additionally, we would like to post the oscap result xml to an API of the central security reporting system or fetch it from a central storage location per cluster. From our side, we're planning to integrate the output of the compliance operator into an enterprise wide security reporting system. 
In terms of scope of the report, we currently (OpenShift Version 3.11) rely on the openSCAP oval result files for generating the enterprise wide security report.

**Comment by JAORMX** [comment]
@emergency6300 the XML output is already stored in a persistent volume claim in the cluster. You can clone it, make backups, or even get a pod to mount it and serve it. Here's more information about that: https://github.com/openshift/compliance-operator#extracting-raw-results

But yes, having a native ability for the operator to do that would be great! I'd like to capture your input better and turn that into appropriate user-stories or even a requirements doc. @emergency6300 @rflorenc any ideas on how to start gathering this? should we start a doc somewhere? This way when we do come up with a solution, we could cover your needs better.

**Comment by emergency6300** [comment]
@JAORMX : Agreed, I'm aware of the pvc option you mentioned. My thought were, that if one is to build some kind of UI to display results, it would 
a) be useful, if there was one UI for all the cluster
b) be easy to expose the raw data (xmls) at a REST endpoint for simple integration into other tools

II'll follow your lead on the docs :) Happy to provide my input. 
Myself I already thought about building some service which parses the CRDs generated by the operator and presents them in the UI. If one was to monitor multiple clusters, it would be possible to run this services in a central admin environment and pull the information through oc commands from different clusters. However, for integration in enterprise tools, the standardised XML output is more handy.

**Comment by rflorenc** [comment]
Hi @JAORMX 

I see it either as part of the operator itself or the oc-compliance plugin.

**Besides report-viewing, what other actions would you do if you had a UI for the operator?**
Personally I'd keep this as simple as possible for now. One page with all the reports generated "pointing" to the individual platform/node scans. 

**Who should have access to look at such reports?**
Users/SA with cluster-admin/reader ? 
Any route exposed should be secured by RBAC / TLS
Any API endpoint exposed should be secured by RBAC / TLS 

**Is there extra information in the report you generated that would be beneficial to have?**
Perhaps the compliancesuite status (Running/Aggregating/Done) that triggered this report.

I've created the below just as a placeholder, feel free to modify add / remove sections.
https://tinyurl.com/y4r95ebz

**Comment by turbra** [comment]
Having the option to generate the reports as html and retrieve them via the usual means would be a great step in the right direction.  Next, presenting the results in the UI with the option to download (or retrieve via an api) them as an html/pdf report would be excellent.

**Comment by JAORMX** [comment]
@turbra we're currently hoping to address that with this oc plugin that's in development: https://github.com/JAORMX/oc-compliance

**Comment by JAORMX** [comment]
We're productizing oc-compliance, and it's now in https://github.com/openshift/oc-compliance/ . That plugin will make it easier to publish ARF results.
