### ISSUE TITLE
Init container images for disconnected environments with private registries

### ISSUE THREAD

**Issue by reggie-k** [openshift/compliance-operator#471]
The compliance-operator deployment has an option to configure RELATED_IMAGE_OPENSCAP, RELATED_IMAGE_OPERATOR. RELATED_IMAGE_PROFILE.
As I run the operator on a disconnected env with a private registry, I altered them to reflect that.
The operator was up fine, but the corresponding deployments it created didn't get those values, resulting in them trying to pull from quay.io, which is not accessible.
The values are not propagated to the operator-created deployments.

**Comment by JAORMX** [comment]
@reggie-k what steps did you take? Did you try installing it from OperatorHub? What version of OpenShift is this?

**Comment by reggie-k** [comment]
Nope, not from OperatorHub, took the release from this repo - release 0.1.19.
OCP version 4.5

**Comment by reggie-k** [comment]
Also, was quite surprised to see that the main images compliance-operator/compliance-operator and the complianceascode/ocp4 are referenced with the latest tag and not a specific one...

**Comment by reggie-k** [comment]
My bad. It is configurable with the CRs.

**Comment by JAORMX** [comment]
> Also, was quite surprised to see that the main images compliance-operator/compliance-operator and the complianceascode/ocp4 are referenced with the latest tag and not a specific one...

@reggie-k we also have upstream releases that deploy through OperatorHub (you'd need to enable the catalog source as specified in the README instructions), and those point to specific release tags.

**Comment by reggie-k** [comment]
So I managed to get most of it working by setting the correct image in the example-compliancesuite.
The only thing that still looks for images from quay is the init container content-container in example-compliancescan-api-checks-pod.
Where can it be configured?

**Comment by JAORMX** [comment]
@reggie-k yes, that's configurable. How did you deploy that scan?

**Comment by reggie-k** [comment]
Actually looks like it was created by the operator itself... For now I just deployed all the provided CRs and didn't create any of my own. Applied the crd folder as was and only changed the image names where was necessary. Release 0.1.19

**Comment by JAORMX** [comment]
@reggie-k when deploying from source, you don't want to apply the whole `crd/` folder. There are instructions in the README: https://github.com/openshift/compliance-operator#deploying-from-source

That folder contains some examples and you probably don't want those objects created in your cluster by default.

The operator itself doesn't create scans by default, those need to be created by the user.

Given that you're in a disconnected environment, you probably want to create a `ProfileBundle` object that points to the image you're mirroring: https://github.com/openshift/compliance-operator/blob/master/doc/crds.md#the-profilebundle-object

that'll eventually parse the content and create relevant `Profile` objects that you can take into use to scan. The operator will then use the right image.

**Comment by JAORMX** [comment]
@reggie-k any updates?

**Comment by reggie-k** [comment]
I think I will wait a bit, to install 4.6 and then see how the operator is installed from operator hub. Closing the issue
