### ISSUE TITLE
ocp4-cis failed when using OVN plugin

### ISSUE THREAD

**Issue by amelie1979** [openshift/compliance-operator#525]
When cluster is configure to use Openshift OVN (Kubernetes plugin), the result is not compliant (OVS should not be applicable when using OVN plugin)

[kni@metal01 0]$ oc get compliancecheckresults | grep -i fail
ocp4-cis-node-master-file-groupowner-ovs-conf-db                      FAIL     medium
ocp4-cis-node-master-file-permissions-multus-conf                     FAIL     medium
ocp4-cis-node-master-file-permissions-ovs-conf-db                     FAIL     medium
ocp4-cis-node-worker-file-groupowner-ovs-conf-db                      FAIL     medium
ocp4-cis-node-worker-file-permissions-multus-conf                     FAIL     medium
ocp4-cis-node-worker-file-permissions-ovs-conf-db                     FAIL     medium

**Comment by JAORMX** [comment]
@amelie1979 Thanks for reporting this! We'll check this out!

Do you happen to know if OVN puts some files on the RHCOS filesystem that we could detect?

**Comment by JAORMX** [comment]
@amelie1979 for now it is possible to create a `TailoredProfile` that merely disables those rules. But we'll look into fixing the checks so they only run if ovs is there.

**Comment by amelie1979** [comment]
Thank I will look into the TailoredProfile feature

**Comment by JAORMX** [comment]
@amelie1979 what's the OCP version?

**Comment by JAORMX** [comment]
We adjusted the content in ComplianceAsCode to work in this. Closing as it should be fixed already.
