### ISSUE TITLE
most platform checks fail because of missing configmap

### ISSUE THREAD

**Issue by zrlvep** [openshift/compliance-operator#542]
Hi all

Not sure whether this is the right place to ask such a question. Feel free to redirect me to other channels if needed.

I run an OpenShift cluster 4.3 on IBM Cloud which is built on top of RHEL nodes. 

I installed the compliance operator and wanted to assess the platform compliance posture. Pretty much all of the ocp4 checks fail, so I started investigating. 
From the `ssg-ocp4-ds.xml` file I saw that e.g. the api-server checks are all based around the evaluation of a configmap `config` in different namespaces i.e. `oc get configmap config -n openshift-apiserver -ojson | jq -r '.data["config.yaml"]' | jq '.apiServerArguments["audit-log-path"]'`. The problem is, a configmap called `config` does not exist on my cluster, in any namespace. 

Any clue what I'm doing wrong or what I'm missing?

**Comment by JAORMX** [comment]
> Hi all
> 
> Not sure whether this is the right place to ask such a question. Feel free to redirect me to other channels if needed.

This is the right channel. I'll do my best to help!

> 
> I run an OpenShift cluster 4.3 on IBM Cloud which is built on top of RHEL nodes.

Note that the Compliance Operator is targetted at OpenShift 4.6+, so there really is no support for 4.3... Namely, remediations won't work. Also, while you can use RHEL content, we do focus on checks for RHCOS.
> 
> I installed the compliance operator and wanted to assess the platform compliance posture. Pretty much all of the ocp4 checks fail, so I started investigating.
> From the `ssg-ocp4-ds.xml` file I saw that e.g. the api-server checks are all based around the evaluation of a configmap `config` in different namespaces i.e. `oc get configmap config -n openshift-apiserver -ojson | jq -r '.data["config.yaml"]' | jq '.apiServerArguments["audit-log-path"]'`. The problem is, a configmap called `config` does not exist on my cluster, in any namespace.

Right, the `config` ConfigMap is an instance of the openshift apiserver configuration, that exists in 4.6+ but I'm not sure how it was done back in 4.3. It has to be in the `openshift-apiserver` namespace as that's where the cluster-openshift-apiserver-operator reads it from in order to deploy the relevant operator.
> 
> Any clue what I'm doing wrong or what I'm missing?

**Comment by zrlvep** [comment]
Thanks a lot for that, that would make perfect sense. I propose to add this to the README, I didn't see that it mentions a particular required OpenShift version.

**Comment by zrlvep** [comment]
If I use the RHEL7 contentfile, will I see proper results for node scans although running OpenShift 4.3?

**Comment by JAORMX** [comment]
@zrlvep right, you'll see proper results for node scans if you do use rhel7 content files. I suggest creating a `ProfileBundle` that points to a container image with the appropriate files for this [1]. Subsequently, you can use a `ScanSettingBinding` to take the profiles generated by that bundle into use [2], this is just to get the operator to automate the OpenSCAP parameter setup. It's a slightly nicer UX.

[1] https://github.com/openshift/compliance-operator/blob/master/doc/crds.md#the-profilebundle-object
[2] https://github.com/openshift/compliance-operator/blob/master/doc/crds.md#the-scansetting-and-scansettingbinding-objects

**Comment by zrlvep** [comment]
Ok thanks. I already did that some time ago and I think the only issue I had, was that the rhel7 node scan only work once and consecutive scans will return errors (But I might be mistaken). I saw that RHEL7 is not officially supported so I started playing with the platform scans. I will try again with the rhel7 scans and report back any findings.

**Comment by zrlvep** [comment]
@JAORMX Would it be possible to add the OpenShift version requirement to the README here?

Also, when evaluating the node scans I found that the check `rhel7-file-permissions-ungroupowned` will result in an error result of the scan with the following msg:
```
  errormsg: "Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
    ... ok\nTitle\r\tEnsure All Files Are Owned by a Group\nRule\r\txccdf_org.ssgproject.content_rule_file_permissions_ungroupowned\nIdent\r\tCCE-80135-7\n/usr/bin/oscap-chroot:
    line 100:    11 Killed                  oscap \"$@\"\n"
```

**Comment by JAORMX** [comment]
> @JAORMX Would it be possible to add the OpenShift version requirement to the README here?

will do!

> 
> Also, when evaluating the node scans I found that the check `rhel7-file-permissions-ungroupowned` will result in an error result of the scan with the following msg:
> 
> ```
>   errormsg: "Downloading: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml
>     ... ok\nTitle\r\tEnsure All Files Are Owned by a Group\nRule\r\txccdf_org.ssgproject.content_rule_file_permissions_ungroupowned\nIdent\r\tCCE-80135-7\n/usr/bin/oscap-chroot:
>     line 100:    11 Killed                  oscap \"$@\"\n"
> ```

Can you run the scan with `debug: true` and see if it gives more info? That sounds like an OpenSCAP bug.

**Comment by zrlvep** [comment]
Here you go, output of `oc get compliancescan`: 

>   errormsg: "I: oscap: Identified document type: data-stream-collection\nI: oscap:
    Created a new XCCDF session from a SCAP Source Datastream '/content/ssg-rhel7-ds.xml'.\nDownloading:
    https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml ... ok\nI:
    oscap: Identified document type: Benchmark\nI: oscap: Identified document type:
    cpe-list\nI: oscap: Started new OVAL agent ssg-rhel7-oval.xml.\nI: oscap: Querying
    system information.\nI: oscap: Starting probe on URI 'queue://system_info'.\nI:
    oscap: Switching probe to PROBE_OFFLINE_OWN mode.\nI: oscap: I will run system_info_probe_main:\nI:
    oscap: Started new OVAL agent security-data-oval-com.redhat.rhsa-RHEL7.xml.\nI:
    oscap: Querying system information.\nI: oscap: Starting probe on URI 'queue://system_info'.\nI:
    oscap: Switching probe to PROBE_OFFLINE_OWN mode.\nI: oscap: I will run system_info_probe_main:\nI:
    oscap: Identified document type: Tailoring\nI: oscap: Parsing Tailoring Profiles
    without reference to Benchmark\nI: oscap: Evaluating a XCCDF policy with selected
    'xccdf_compliance.openshift.io_profile_rhel7-ncp-ibm-pi-debug' profile.\nTitle\r\tEnsure
    All Files Are Owned by a Group\nRule\r\txccdf_org.ssgproject.content_rule_file_permissions_ungroupowned\nIdent\r\tCCE-80135-7\nI:
    oscap: Evaluating XCCDF rule 'xccdf_org.ssgproject.content_rule_file_permissions_ungroupowned'.\nI:
    oscap: Started new OVAL agent /usr/share/openscap/cpe/openscap-cpe-oval.xml.\nI:
    oscap: Querying system information.\nI: oscap: Starting probe on URI 'queue://system_info'.\nI:
    oscap: Switching probe to PROBE_OFFLINE_OWN mode.\nI: oscap: I will run system_info_probe_main:\nI:
    oscap: Evaluating definition 'oval:org.open-scap.cpe.rhel:def:7': Red Hat Enterprise
    Linux 7.\nI: oscap:   Evaluating rpmverifyfile test 'oval:org.open-scap.cpe.rhel:tst:7':
    redhat-release is version 7.\nI: oscap:     Querying rpmverifyfile object 'oval:org.open-scap.cpe.redhat-release:obj:3',
    flags: 0.\nI: oscap:     Creating new syschar for rpmverifyfile_object 'oval:org.open-scap.cpe.redhat-release:obj:3'.\nI:
    oscap:     Starting probe on URI 'queue://rpmverifyfile'.\nI: oscap:     Switching
    probe to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpmverifyfile_probe_main:\nI:
    oscap:     Leaving chroot mode\nI: oscap:     Test 'oval:org.open-scap.cpe.rhel:tst:7'
    requires that at least one object defined by 'oval:org.open-scap.cpe.redhat-release:obj:3'
    exists on the system.\nI: oscap:     1 objects defined by 'oval:org.open-scap.cpe.redhat-release:obj:3'
    exist on the system.\nI: oscap:     All items matching object 'oval:org.open-scap.cpe.redhat-release:obj:3'
    were collected. (flag=complete)\nI: oscap:     In test 'oval:org.open-scap.cpe.rhel:tst:7'
    at least one of the collected items must satisfy these states: 'oval:org.open-scap.cpe.rhel:ste:7'.\nI:
    oscap:     Entity 'name'='redhat-release-server' of item '1000104' matches corresponding
    entity in state 'oval:org.open-scap.cpe.rhel:ste:7'.\nI: oscap:     Entity 'version'='7.9'
    of item '1000104' matches corresponding entity in state 'oval:org.open-scap.cpe.rhel:ste:7'.\nI:
    oscap:     Item '1000104' compared to state 'oval:org.open-scap.cpe.rhel:ste:7'
    with result true.\nI: oscap:   Test 'oval:org.open-scap.cpe.rhel:tst:7' evaluated
    as true.\nI: oscap:   Evaluating rpminfo test 'oval:org.open-scap.cpe.rhevh:tst:1':
    redhat-release-virtualization-host RPM package is installed.\nI: oscap:     Querying
    rpminfo object 'oval:org.open-scap.cpe.rhevh:obj:1', flags: 0.\nI: oscap:     Creating
    new syschar for rpminfo_object 'oval:org.open-scap.cpe.rhevh:obj:1'.\nI: oscap:
    \    Starting probe on URI 'queue://rpminfo'.\nI: oscap:     Switching probe to
    PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpminfo_probe_main:\nI: oscap:
    \    Package \"redhat-release-virtualization-host\" not found.\nI: oscap:     Leaving
    chroot mode\nI: oscap:     Test 'oval:org.open-scap.cpe.rhevh:tst:1' requires
    that only one object defined by 'oval:org.open-scap.cpe.rhevh:obj:1' exists on
    the system.\nI: oscap:     0 objects defined by 'oval:org.open-scap.cpe.rhevh:obj:1'
    exist on the system.\nI: oscap:     Test 'oval:org.open-scap.cpe.rhevh:tst:1'
    does not contain any state to compare object with.\nI: oscap:     No item matching
    object 'oval:org.open-scap.cpe.rhevh:obj:1' was found on the system. (flag=does
    not exist)\nI: oscap:   Test 'oval:org.open-scap.cpe.rhevh:tst:1' evaluated as
    false.\nI: oscap:   Evaluating textfilecontent54 test 'oval:org.open-scap.cpe.rhevh:tst:2':
    RHEVH base RHEL is version 7.\nI: oscap:     Querying textfilecontent54 object
    'oval:org.open-scap.cpe.rhevh:obj:2', flags: 0.\nI: oscap:     Creating new syschar
    for textfilecontent54_object 'oval:org.open-scap.cpe.rhevh:obj:2'.\nI: oscap:
    \    Starting probe on URI 'queue://textfilecontent54'.\nI: oscap:     Switching
    probe to PROBE_OFFLINE_OWN mode.\nI: oscap:     I will run textfilecontent54_probe_main:\nI:
    oscap:     Opening file '/host/etc/redhat-release'.\nI: oscap:     Test 'oval:org.open-scap.cpe.rhevh:tst:2'
    requires that at least one object defined by 'oval:org.open-scap.cpe.rhevh:obj:2'
    exists on the system.\nI: oscap:     0 objects defined by 'oval:org.open-scap.cpe.rhevh:obj:2'
    exist on the system.\nI: oscap:     No item matching object 'oval:org.open-scap.cpe.rhevh:obj:2'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:org.open-scap.cpe.rhevh:tst:2'
    evaluated as false.\nI: oscap: Definition 'oval:org.open-scap.cpe.rhel:def:7'
    evaluated as true.\nI: oscap: Started new OVAL agent ssg-rhel7-cpe-oval.xml.\nI:
    oscap: Querying system information.\nI: oscap: Starting probe on URI 'queue://system_info'.\nI:
    oscap: Switching probe to PROBE_OFFLINE_OWN mode.\nI: oscap: I will run system_info_probe_main:\nI:
    oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhel7:def:1': Red Hat Enterprise
    Linux 7.\nI: oscap:   Evaluating family test 'oval:ssg-test_rhel7_unix_family:tst:1':
    installed OS part of unix family.\nI: oscap:     Querying family object 'oval:ssg-obj_rhel7_unix_family:obj:1',
    flags: 0.\nI: oscap:     Creating new syschar for family_object 'oval:ssg-obj_rhel7_unix_family:obj:1'.\nI:
    oscap:     Starting probe on URI 'queue://family'.\nI: oscap:     Switching probe
    to PROBE_OFFLINE_OWN mode.\nI: oscap:     I will run family_probe_main:\nI: oscap:
    \    Test 'oval:ssg-test_rhel7_unix_family:tst:1' requires that at least one object
    defined by 'oval:ssg-obj_rhel7_unix_family:obj:1' exists on the system.\nI: oscap:
    \    1 objects defined by 'oval:ssg-obj_rhel7_unix_family:obj:1' exist on the
    system.\nI: oscap:     All items matching object 'oval:ssg-obj_rhel7_unix_family:obj:1'
    were collected. (flag=complete)\nI: oscap:     In test 'oval:ssg-test_rhel7_unix_family:tst:1'
    all of the collected items must satisfy these states: 'oval:ssg-state_rhel7_unix_family:ste:1'.\nI:
    oscap:     Entity 'family'='unix' of item '1000106' matches corresponding entity
    in state 'oval:ssg-state_rhel7_unix_family:ste:1'.\nI: oscap:     Item '1000106'
    compared to state 'oval:ssg-state_rhel7_unix_family:ste:1' with result true.\nI:
    oscap:   Test 'oval:ssg-test_rhel7_unix_family:tst:1' evaluated as true.\nI: oscap:
    \  Evaluating rpminfo test 'oval:ssg-test_rhel7_client:tst:1': redhat-release-client
    is version 7.\nI: oscap:     Querying rpminfo object 'oval:ssg-obj_rhel7_client:obj:1',
    flags: 0.\nI: oscap:     Creating new syschar for rpminfo_object 'oval:ssg-obj_rhel7_client:obj:1'.\nI:
    oscap:     Starting probe on URI 'queue://rpminfo'.\nI: oscap:     Switching probe
    to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpminfo_probe_main:\nI:
    oscap:     Package \"redhat-release-client\" not found.\nI: oscap:     Leaving
    chroot mode\nI: oscap:     Test 'oval:ssg-test_rhel7_client:tst:1' requires that
    at least one object defined by 'oval:ssg-obj_rhel7_client:obj:1' exists on the
    system.\nI: oscap:     0 objects defined by 'oval:ssg-obj_rhel7_client:obj:1'
    exist on the system.\nI: oscap:     No item matching object 'oval:ssg-obj_rhel7_client:obj:1'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:ssg-test_rhel7_client:tst:1'
    evaluated as false.\nI: oscap:   Evaluating rpminfo test 'oval:ssg-test_rhel7_workstation:tst:1':
    redhat-release-workstation is version 7.\nI: oscap:     Querying rpminfo object
    'oval:ssg-obj_rhel7_workstation:obj:1', flags: 0.\nI: oscap:     Creating new
    syschar for rpminfo_object 'oval:ssg-obj_rhel7_workstation:obj:1'.\nI: oscap:
    \    Switching probe to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpminfo_probe_main:\nI:
    oscap:     Package \"redhat-release-workstation\" not found.\nI: oscap:     Leaving
    chroot mode\nI: oscap:     Test 'oval:ssg-test_rhel7_workstation:tst:1' requires
    that at least one object defined by 'oval:ssg-obj_rhel7_workstation:obj:1' exists
    on the system.\nI: oscap:     0 objects defined by 'oval:ssg-obj_rhel7_workstation:obj:1'
    exist on the system.\nI: oscap:     No item matching object 'oval:ssg-obj_rhel7_workstation:obj:1'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:ssg-test_rhel7_workstation:tst:1'
    evaluated as false.\nI: oscap:   Evaluating rpminfo test 'oval:ssg-test_rhel7_server:tst:1':
    redhat-release-server is version 7.\nI: oscap:     Querying rpminfo object 'oval:ssg-obj_rhel7_server:obj:1',
    flags: 0.\nI: oscap:     Creating new syschar for rpminfo_object 'oval:ssg-obj_rhel7_server:obj:1'.\nI:
    oscap:     Switching probe to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will
    run rpminfo_probe_main:\nI: oscap:     Leaving chroot mode\nI: oscap:     Test
    'oval:ssg-test_rhel7_server:tst:1' requires that at least one object defined by
    'oval:ssg-obj_rhel7_server:obj:1' exists on the system.\nI: oscap:     1 objects
    defined by 'oval:ssg-obj_rhel7_server:obj:1' exist on the system.\nI: oscap:     All
    items matching object 'oval:ssg-obj_rhel7_server:obj:1' were collected. (flag=complete)\nI:
    oscap:     In test 'oval:ssg-test_rhel7_server:tst:1' all of the collected items
    must satisfy these states: 'oval:ssg-state_rhel7_server:ste:1'.\nI: oscap:     Entity
    'version'='7.9' of item '1000107' matches corresponding entity in state 'oval:ssg-state_rhel7_server:ste:1'.\nI:
    oscap:     Item '1000107' compared to state 'oval:ssg-state_rhel7_server:ste:1'
    with result true.\nI: oscap:   Test 'oval:ssg-test_rhel7_server:tst:1' evaluated
    as true.\nI: oscap:   Evaluating rpminfo test 'oval:ssg-test_rhel7_computenode:tst:1':
    redhat-release-computenode is version 7.\nI: oscap:     Querying rpminfo object
    'oval:ssg-obj_rhel7_computenode:obj:1', flags: 0.\nI: oscap:     Creating new
    syschar for rpminfo_object 'oval:ssg-obj_rhel7_computenode:obj:1'.\nI: oscap:
    \    Switching probe to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpminfo_probe_main:\nI:
    oscap:     Package \"redhat-release-computenode\" not found.\nI: oscap:     Leaving
    chroot mode\nI: oscap:     Test 'oval:ssg-test_rhel7_computenode:tst:1' requires
    that at least one object defined by 'oval:ssg-obj_rhel7_computenode:obj:1' exists
    on the system.\nI: oscap:     0 objects defined by 'oval:ssg-obj_rhel7_computenode:obj:1'
    exist on the system.\nI: oscap:     No item matching object 'oval:ssg-obj_rhel7_computenode:obj:1'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:ssg-test_rhel7_computenode:tst:1'
    evaluated as false.\nI: oscap:   Evaluating rpminfo test 'oval:ssg-test_rhvh4_version:tst:1':
    redhat-release-virtualization-host RPM package is installed.\nI: oscap:     Querying
    rpminfo object 'oval:ssg-obj_rhvh4_version:obj:1', flags: 0.\nI: oscap:     Creating
    new syschar for rpminfo_object 'oval:ssg-obj_rhvh4_version:obj:1'.\nI: oscap:
    \    Switching probe to PROBE_OFFLINE_CHROOT mode.\nI: oscap:     I will run rpminfo_probe_main:\nI:
    oscap:     Package \"redhat-release-virtualization-host\" not found.\nI: oscap:
    \    Leaving chroot mode\nI: oscap:     Test 'oval:ssg-test_rhvh4_version:tst:1'
    requires that only one object defined by 'oval:ssg-obj_rhvh4_version:obj:1' exists
    on the system.\nI: oscap:     0 objects defined by 'oval:ssg-obj_rhvh4_version:obj:1'
    exist on the system.\nI: oscap:     No item matching object 'oval:ssg-obj_rhvh4_version:obj:1'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:ssg-test_rhvh4_version:tst:1'
    evaluated as false.\nI: oscap:   Evaluating textfilecontent54 test 'oval:ssg-test_rhevh_rhel7_version:tst:1':
    RHEVH base RHEL is version 7.\nI: oscap:     Querying textfilecontent54 object
    'oval:ssg-obj_rhevh_rhel7_version:obj:1', flags: 0.\nI: oscap:     Creating new
    syschar for textfilecontent54_object 'oval:ssg-obj_rhevh_rhel7_version:obj:1'.\nI:
    oscap:     Starting probe on URI 'queue://textfilecontent54'.\nI: oscap:     Switching
    probe to PROBE_OFFLINE_OWN mode.\nI: oscap:     I will run textfilecontent54_probe_main:\nI:
    oscap:     Opening file '/host/etc/redhat-release'.\nI: oscap:     Test 'oval:ssg-test_rhevh_rhel7_version:tst:1'
    requires that at least one object defined by 'oval:ssg-obj_rhevh_rhel7_version:obj:1'
    exists on the system.\nI: oscap:     0 objects defined by 'oval:ssg-obj_rhevh_rhel7_version:obj:1'
    exist on the system.\nI: oscap:     No item matching object 'oval:ssg-obj_rhevh_rhel7_version:obj:1'
    was found on the system. (flag=does not exist)\nI: oscap:   Test 'oval:ssg-test_rhevh_rhel7_version:tst:1'
    evaluated as false.\nI: oscap: Definition 'oval:ssg-installed_OS_is_rhel7:def:1'
    evaluated as true.\nI: oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhel7:def:1':
    Red Hat Enterprise Linux 7.\nI: oscap: Definition 'oval:ssg-installed_OS_is_rhel7:def:1'
    evaluated as true.\nI: oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhel7:def:1':
    Red Hat Enterprise Linux 7.\nI: oscap: Definition 'oval:ssg-installed_OS_is_rhel7:def:1'
    evaluated as true.\nI: oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhel7:def:1':
    Red Hat Enterprise Linux 7.\nI: oscap: Definition 'oval:ssg-installed_OS_is_rhel7:def:1'
    evaluated as true.\nI: oscap: Evaluating definition 'oval:ssg-installed_OS_is_rhel7:def:1':
    Red Hat Enterprise Linux 7.\nI: oscap: Definition 'oval:ssg-installed_OS_is_rhel7:def:1'
    evaluated as true.\nI: oscap: This rule requires an OCIL check. OCIL checks are
    not supported by OpenSCAP.\nI: oscap: Evaluating definition 'oval:ssg-file_permissions_ungroupowned:def:1':
    Ensure All Files Are Owned by a Group.\nI: oscap:   Evaluating file test 'oval:ssg-test_file_permissions_ungroupowned:tst:1':
    files with no group owner.\nI: oscap:     Querying file object 'oval:ssg-object_file_permissions_ungroupowned:obj:1',
    flags: 0.\nI: oscap:     Creating new syschar for file_object 'oval:ssg-object_file_permissions_ungroupowned:obj:1'.\nI:
    oscap:     Starting probe on URI 'queue://file'.\nI: oscap:     Object 'oval:ssg-object_file_permissions_ungroupowned:obj:1'
    has a filter that excludes items conforming to state 'oval:ssg-state_file_permissions_ungroupowned:ste:1'.\nI:
    oscap:     Switching probe to PROBE_OFFLINE_OWN mode.\nI: oscap:     Querying
    variable 'oval:ssg-variable_file_permissions_ungroupowned:var:1'.\nI: oscap:     Variable
    component references to object 'oval:ssg-etc_group_object:obj:1'.\nI: oscap:     Querying
    textfilecontent54 object 'oval:ssg-etc_group_object:obj:1', flags: 0.\nI: oscap:
    \    Creating new syschar for textfilecontent54_object 'oval:ssg-etc_group_object:obj:1'.\nI:
    oscap:     Starting probe on URI 'queue://textfilecontent54'.\nI: oscap:     Switching
    probe to PROBE_OFFLINE_OWN mode.\nI: oscap:     I will run textfilecontent54_probe_main:\nI:
    oscap:     Opening file '/host/etc/group'.\nI: oscap:     Variable 'oval:ssg-variable_file_permissions_ungroupowned:var:1'
    has values \"0\", \"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\",
    \"10\", \"11\", \"12\", \"15\", \"18\", \"19\", \"20\", \"30\", \"39\", \"50\",
    \"54\", \"63\", \"99\", \"100\", \"170\", \"22\", \"35\", \"999\", \"998\", \"190\",
    \"997\", \"996\", \"81\", \"995\", \"40\", \"59\", \"90\", \"89\", \"74\", \"994\",
    \"38\", \"188\", \"32\", \"29\", \"65534\".\nI: oscap:     I will run file_probe_main:\nI:
    oscap:     Opening file '/host/'.\nI: oscap:     Object is incomplete due to memory
    constraints.\nI: oscap:     Test 'oval:ssg-test_file_permissions_ungroupowned:tst:1'
    requires that none of the objects defined by 'oval:ssg-object_file_permissions_ungroupowned:obj:1'
    exist on the system.\nI: oscap:     786840 objects defined by 'oval:ssg-object_file_permissions_ungroupowned:obj:1'
    exist on the system.\nI: oscap:     Test 'oval:ssg-test_file_permissions_ungroupowned:tst:1'
    does not contain any state to compare object with.\nI: oscap:     Only some of
    items matching object 'oval:ssg-object_file_permissions_ungroupowned:obj:1' have
    been collected from the system. It is unknown if other matching items also exist.
    (flag=incomplete)\nI: oscap:   Test 'oval:ssg-test_file_permissions_ungroupowned:tst:1'
    evaluated as false.\nI: oscap: Definition 'oval:ssg-file_permissions_ungroupowned:def:1'
    evaluated as false.\n/usr/bin/oscap-chroot: line 100:    10 Killed                  oscap
    \"$@\"\n"

**Comment by zrlvep** [comment]
Hey @JAORMX another thing about the platform scans. I wanted to try and "trick" the operator into reporting compliant state for demo purpose by adding the config maps myself on the 4.3 cluster. I created the following configmap 
```
$oc get configmap config -n openshift-apiserver -o json

{
    "apiVersion": "v1",
    "data": {
        "config.yaml": "{ \n  \"auditConfig\": {\n    \"maximumRetainedFiles\": 10,\n    \"maximumFileRetentionDays\": 90\n   },\n  \"apiServerArguments\": {\n    \"maximumFileSizeMegabytes\": 100,\n    \"audit-log-maxbackup\": [\n       10\n     ]\n  }\n}\n"
    },
    "kind": "ConfigMap",
    "metadata": {
        "creationTimestamp": "2021-01-21T16:15:08Z",
        "name": "config",
        "namespace": "openshift-apiserver",
        "resourceVersion": "20746984",
        "selfLink": "/api/v1/namespaces/openshift-apiserver/configmaps/config",
        "uid": "66457b5a-2f46-46c7-b4ed-731504201938"
    }
}
```
so it would pass the check I found in the ssg-ocp4-ds.xml 
```
$oc get configmap config -n openshift-kube-apiserver -ojson | jq -r '.data["config.yaml"]' | jq '.apiServerArguments["maximumFileSizeMegabytes"]'
10
````
I created a profile with exactly one check in it `ocp-api-server-audit-log-maxsize`
but the msg in the compliancescan still says:
```
 warnings: |-
    the server could not find the requested resource
    the server could not find the requested resource
    configmaps "config" not found
    configmaps "config" not found
    configmaps "config" not found
    configmaps "config" not found
    configmaps "config" not found
    configmaps "config" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "etcd-pod" not found
    configmaps "kube-scheduler-pod" not found
```

Does the check more than just check the configmap? Any idea what I could do to "trick" the operator?

**Comment by JAORMX** [comment]
@zrlvep we check every relevant configuration in OpenShift so that `config` ConfigMap might not be the only one... It's hard to keep track of all the content we've written. Honestly, I don't think it's trivial to trick the operator to make it work in 4.3 :confused:
