### ISSUE TITLE
Not able to list outdated-remediation

### ISSUE THREAD

**Issue by hugohdz89** [openshift/compliance-operator#545]
Hello team

This is the history, I had a tailored profile and we patched only few remediations. We deleted that tailored profile and used a full profile to scan/remediate everything.

However it seems some remediations applied in the past, are outdated and I can't update those remediations because I've deleted the old tailored-profile and the complianceremediations are gone.

So when trying to get the outdated-remediations I can't find anything, however the compliance scan is informing about this.

<img width="1874" alt="image" src="https://user-images.githubusercontent.com/16210206/105393244-bce7a900-5be1-11eb-9ba4-20e7e4775adf.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/16210206/105393281-c6711100-5be1-11eb-9c18-f45fad882062.png">

I'm following instructions from here https://docs.openshift.com/container-platform/4.6/security/compliance_operator/compliance-operator-remediation.html

Hopefully there's another way to move forward on this.

**Comment by JAORMX** [comment]
Sounds like we might have missed a label in the code. We'll look into this!

In the meantime, doing:

```
oc get complianceremediations | grep -i outdate
```

would show you which remediations they are.

**Comment by hugohdz89** [comment]
Hello @JAORMX 

When the complianceremediations are still there, they are listed as Applied NotApplied or Outdate

However, when I removed the tailored profile and re-created it again, the complianceremediations applied in the past, are not being generated again, even if those were in Outdated state.

However, I was able to generate the complianceremediations back, when I deleted the profile and the machineconfigs created based on the complianceremediations. Then scanned the cluster again and the compliance remediations appeared.

Just wondering now, why if I've applied all the remediations, I'm still getting many FAILs.

![image](https://user-images.githubusercontent.com/16210206/105504820-d34b3e80-5c8d-11eb-870f-80ff775c80aa.png)

![image](https://user-images.githubusercontent.com/16210206/105504865-e1995a80-5c8d-11eb-842e-b4c96a18703d.png)

The machine configs were created, the nodes were rebooted by the MachineConfigPool. The changes are listed under the rendered-master and rendered-worker config files.

Also, I've used the oc-compliance plugin to check the view-result option.

 hhmoran@Hugos-MacBook-Pro  ~  oc compliance view-result rhcos4-e8-master-audit-rules-execution-chcon
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
|         KEY          |                                                                     VALUE                                                                     |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| title                | Record Any Attempts to Run                                                                                                                    |
|                      | chcon                                                                                                                                         |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
**| status               | FAIL                                                                                                                                          |**
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| severity             | medium                                                                                                                                        |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| description          | <code>chcon</code><code>auditd</code><code>augenrules</code><code>.rules</code><code>/etc/audit/rules.d</code><pre>-a                         |
|                      | always,exit -F path=/usr/bin/chcon -F auid&gt;=1000 -F auid!=unset -F                                                                         |
|                      | key=privileged</pre><code>auditd</code><code>auditctl</code><code>/etc/audit/audit.rules</code><pre>-a always,exit -F                         |
|                      | path=/usr/bin/chcon -F auid&gt;=1000 -F auid!=unset -F key=privileged</pre>file:                                                              |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| rationale            | <br /><br />Privileged                                                                                                                        |
|                      | programs are subject to                                                                                                                       |
|                      | escalation-of-privilege                                                                                                                       |
|                      | attacks,&#xA;which attempt                                                                                                                    |
|                      | to subvert their normal role                                                                                                                  |
|                      | of providing some necessary                                                                                                                   |
|                      | but&#xA;limited capability.                                                                                                                   |
|                      | As such, motivation exists                                                                                                                    |
|                      | to monitor these programs                                                                                                                     |
|                      | for&#xA;unusual activity.                                                                                                                     |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| NIST-800-53 Controls | AU-2(d), AU-12(c), AC-6(9),                                                                                                                   |
|                      | CM-6(a)                                                                                                                                       |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
**| Avalailable Fix      | Yes                                                                                                                                           |**
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Fix Object           | ---                                                                                                                                           |
|                      |                                                                                                                                               |
|                      | apiVersion:                                                                                                                                   |
|                      | machineconfiguration.openshift.io/v1                                                                                                          |
|                      |                                                                                                                                               |
|                      | kind: MachineConfig                                                                                                                           |
|                      |                                                                                                                                               |
|                      | spec:                                                                                                                                         |
|                      |                                                                                                                                               |
|                      |   config:                                                                                                                                     |
|                      |                                                                                                                                               |
|                      |     ignition:                                                                                                                                 |
|                      |                                                                                                                                               |
|                      |       version: 3.1.0                                                                                                                          |
|                      |                                                                                                                                               |
|                      |     storage:                                                                                                                                  |
|                      |                                                                                                                                               |
|                      |       files:                                                                                                                                  |
|                      |                                                                                                                                               |
|                      |       - contents:                                                                                                                             |
|                      |                                                                                                                                               |
|                      |           source:                                                                                                                             |
|                      | data:,-a%20always%2Cexit%20-F%20path%3D/usr/bin/chcon%20-F%20perm%3Dx%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-F%20key%3Dprivileged%0A |
|                      |                                                                                                                                               |
|                      |         mode: 420                                                                                                                             |
|                      |                                                                                                                                               |
|                      |         overwrite: true                                                                                                                       |
|                      |                                                                                                                                               |
|                      |         path:                                                                                                                                 |
|                      | /etc/audit/rules.d/75-usr_bin_chcon_execution.rules                                                                                           |
|                      |                                                                                                                                               |
|                      |                                                                                                                                               |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Result Object Name   | rhcos4-e8-master-audit-rules-execution-chcon                                                                                                  |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Rule Object Name     | rhcos4-audit-rules-execution-chcon                                                                                                            |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
**| Remediation Created  | Yes                                                                                                                                           |**
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
| Remediation Name     | rhcos4-e8-master-audit-rules-execution-chcon                                                                                                  |
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+
**| Remediation Status   | Applied                                                                                                                                       |**
+----------------------+-----------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by jhrozek** [comment]
What is the content image you are running? There were some fixes recently that touched some of the audit rules

**Comment by hugohdz89** [comment]
Hello Jhrozek!
The bellow complianceremediations are not properly fixed.
rhcos4-e8-master-audit-rules-execution-chcon               Outdated
rhcos4-e8-master-audit-rules-execution-restorecon          Outdated
rhcos4-e8-master-audit-rules-execution-semanage            Outdated
rhcos4-e8-master-audit-rules-execution-setfiles            Outdated
rhcos4-e8-master-audit-rules-execution-setsebool           Outdated
rhcos4-e8-master-audit-rules-execution-seunshare           Outdated

All the above remediations add some changes under /etc/audit/rules.d/*.rules , however the lines or fixes suggested, included an option "-F perm=x", when I apply the fix, the check fails.
The check is expecting the same line on the remediation without "-F perm=x"

As workaround, I've edited the above complianceremediations as bellow.
Source:   data:,-a%20always%2Cexit%20-F%20path%3D/usr/bin/chcon%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-F%20key%3Dprivileged%0A

This triggered a change in the initial MachineConfig created by this item, and the compliancecheckresults shows a PASS.

As you may notice, the complianceremediation are in Outdated state, the correct/suggested change is bellow

Source:   data:,-a%20always%2Cexit%20-F%20path%3D/usr/bin/chcon**%20-F%20perm%3Dx**%20-F%20auid%3E%3D1000%20-F%20auid%21%3Dunset%20-F%20key%3Dprivileged%0A

However, when looking at the results in HTML, I see this

![image](https://user-images.githubusercontent.com/16210206/105861834-c0e64300-5fb4-11eb-8225-e5a824af5f6f.png)

Not sure if the complianceremediation must have removed the "-F perm=x", or instead, the compliancecheckresult must be updated to look for the "-F perm=x" flag within the above items.

**Comment by JAORMX** [comment]
@hugohdz89 we recently fixed those here https://github.com/ComplianceAsCode/content/pull/6552 and they'll show up as "outdated" once you get the update. To get the operator to apply the up-to-date remediations, you need to delete the "outdated" object in the remediation... but this needs to be done for each outdated remediation, so it gets quite tedious. So, we're working on an annotation to handle this automatically: https://github.com/openshift/compliance-operator/pull/546

**Comment by hugohdz89** [comment]
Hello @JAORMX thanks for the response!

However.. not sure if I missed something, I've worked in these remediations just yesterday... do I need to do something to update the image used by the compliance operator or trigger any action to get the latest updates?

You says I need to delete (literally) the complianceremediation outdated object and it will be regenerated? Or just need to unapply each one of those?

**Comment by JAORMX** [comment]
> Hello @JAORMX thanks for the response!
> 
> However.. not sure if I missed something, I've worked in these remediations just yesterday... do I need to do something to update the image used by the compliance operator or trigger any action to get the latest updates?

If it's a downstream build, no, you don't need to do anything, updates will come automatically. It's a matter of us releasing a newer version of the operator and/or content... which we're working on.

> 
> You says I need to delete (literally) the complianceremediation outdated object and it will be regenerated? Or just need to unapply each one of those?

@hugohdz89 sorry for the confusion. The remediation object contains two objects: `current` and `outdated`. It indicates what the current remediation is, and which was the one that it was applying. To fix this issue, on the remediation object do `oc edit complianceremediation <name>`, and remove the `outdated` block. This will get the operator to apply the `current` one. It was meant to force admins to audit the remediations, but seems to be quite a tedious workflow.

**Comment by hugohdz89** [comment]
Oh Okay!

However as I said, yesterday I worked in these remediations and got the FAIL I listed in a previous update.

I'll give a try and let yo know how it goes.

THanks!

**Comment by hugohdz89** [comment]
@JAORMX Just checked the same profile in another cluster

![image](https://user-images.githubusercontent.com/16210206/105875394-5be61980-5fc3-11eb-9282-62520f6414e4.png)

The remediations are OK, not outdated state, however the check is still failing.

The check doesn't match with the remediation.

Let me know if you need more information.

**Comment by JAORMX** [comment]
@hugohdz89 right, that issue has been triaged and fixed in the ComplianceAsCode project https://github.com/ComplianceAsCode/content/pull/6552 . We are yet to release a new version of the operator so the new rules with the appropriate remediations haven't been released yet. We'll try to release as soon as possible but are currently blocked since we need https://github.com/openshift/compliance-operator/pull/546 to merge

**Comment by JAORMX** [comment]
This should be addressed by https://github.com/openshift/compliance-operator/pull/546  https://github.com/openshift/compliance-operator/pull/563 and https://github.com/openshift/compliance-operator/pull/596
