### ISSUE TITLE
RFE: Scan the rhcos4 host with OVAL data

### ISSUE THREAD

**Issue by jasinner** [openshift/compliance-operator#577]
Currently (at OCP 4.7), RHCOS is built with RPMs from the [OpenShift](https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.oval.xml.bz2) and [RHEL-8](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2). Let's add an rhcos4-oval profile which scans deployed RHCOS hosts with those OVAL streams.

Earlier supported version of RHCOS (before OCP 4.7) where using RHEL-8.2-EUS so we should either not support those versions, or scan instead with the [RHEL-8.2-EUS oval data](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-eus.oval.xml.bz2).

**Comment by jasinner** [comment]
Some changes where made to OVAL to accommodate RHCOS 4 for [all the RHEL-8 files](https://www.redhat.com/security/data/oval/v2/RHEL8/). There should be not blockers to adding this feature now. 

Just need to hardcode which actual OVAL files to use based on what's in the RHCOS compose files for each OCP major release. RHCOS team are going to expose content_set style mapping for these in a future release of RHCOS.

**Comment by JAORMX** [comment]
> Just need to hardcode which actual OVAL files to use based on what's in the RHCOS compose files for each OCP major release. RHCOS team are going to expose content_set style mapping for these in a future release of RHCOS.

@jasinner is this being tracked anywhere? Would be useful to follow that work as a dependency for this.

**Comment by jasinner** [comment]
@ashcrow might know if it's being tracked anywhere publicly. Unfortunately I think they would be RH internal links. At least the repos being used to compose RHCOS are maintained in an internal RH repository. I took a look at the repos for released versions of OCP and can summarize the OVAL files needed as:

4.7
- [RHEL8/rhel-8.oval.xml.bz2 ](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.oval.xml.bz2)
- [RHEL8/openshift-4.7.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.7.oval.xml.bz2)
- [RHEL8/fast-datapath.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/fast-datapath.oval.xml.bz2)

4.6
- [RHEL8/rhel-8.2-tus.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-tus.oval.xml.bz2)
- [RHEL8/rhel-8.2-eus.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-eus.oval.xml.bz2)
- [RHEL8/openshift-4.6.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.6.oval.xml.bz2)
- [RHEL8/fast-datapath.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/fast-datapath.oval.xml.bz2)

4.5
- [RHEL8/rhel-8.2-tus.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-tus.oval.xml.bz2)
- [RHEL8/rhel-8.2-eus.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-eus.oval.xml.bz2)
- [RHEL8/openshift-4.5.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.5.oval.xml.bz2)
- [RHEL8/openshift-4.4.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.4.oval.xml.bz2)
- [RHEL8/fast-datapath.oval.xml.bz2](https://www.redhat.com/security/data/oval/v2/RHEL8/fast-datapath.oval.xml.bz2)

**Comment by ashcrow** [comment]
Am I reading right in that mapping the the OCP `major.minor` with RHEL `major.minor` would answer the question?

**Comment by jasinner** [comment]
> Am I reading right in that mapping the the OCP `major.minor` with RHEL `major.minor` would answer the question?

That would be a good idea to avoid having to modify the rhel-8 OVAL files to also check for RHCOS. As it stands we are doing that in OVAL, but I'd like to remove that monkey patch in future.

**Comment by ashcrow** [comment]
Fair. Today one can get the major./minor this way but it's not as obvious and is probably similar to the monkey patch you're using:

`rpm --queryformat "%{NAME} %{VERSION}\n" -q redhat-release-coreos | cut -d . -f 2 ` == 83 == RHEL 8.3

@cgwalters I'm curious what your thoughts are here.

**Comment by cgwalters** [comment]
> At least the repos being used to compose RHCOS are maintained in an internal RH repository. 

As of 4.7+ https://github.com/openshift/os/ is a thing and while there's still an internal build and repo that can change some things, the input set of repositories is intended to match between that repo and internal.  And specifically e.g. https://github.com/openshift/os/blob/fde7db41094b938765d1a1eb9f3edb99b202b36d/manifest.yaml#L27 is canonical.

Anyways specifically for this problem a while ago we added:

```
$ (. /usr/lib/os-release && echo $RHEL_VERSION)
8.4
$
```

And there's also `OPENSHIFT_VERSION`.

**Comment by jasinner** [comment]
Thanks for sharing manifest.yaml repos link from openshift/os. That helps make the composition more transparent. However as discussed I think we still need a [content_set](https://osbs.readthedocs.io/en/latest/users.html?highlight=content_set#content-sets) shipped with RHCOS which exposes this information (utilising entries repo names from [repository-to-cpe.json](https://www.redhat.com/security/data/metrics/repository-to-cpe.json)) for each RHCOS release on disk.

**Comment by jasinner** [comment]
Given the RHEL_VERSION and OPENSHIFT_VERSION are exposed by /usr/lib/os-release command we should be able to use choose the 2 major release streams required for scanning RHCOS, eg:

https://www.redhat.com/security/data/oval/v2/RHEL8/rhel-8.2-eus.oval.xml.bz2
https://www.redhat.com/security/data/oval/v2/RHEL8/openshift-4.7.oval.xml.bz2

One caveat is that if the version of RHEL is returned at 83 we should just not include it, as that EUS stream does not exist and packages where instead shipped directly in the openshift minor stream (4.7).

**Comment by jasinner** [comment]
I put together [this example](https://github.com/RedHatProductSecurity/rhcos-scan) add which scans an RHCOS host. I'd love to expand on this to add for example:

- operator to keep it updated when a new version of rhcos-scan is released
- results CRD similar to what this project has
- a webui to view the scan results in HTML format (probably requires consolidate of results for CRD or similar first)

**Comment by JAORMX** [comment]
> I put together [this example](https://github.com/RedHatProductSecurity/rhcos-scan) app which scans an RHCOS host. I'd love to expand on this to add for example:

I get a 404 error when trying to access this.

> 
>     * operator to keep it updated when a new version of rhcos-scan is released
> 
>     * results CRD similar to what this project has
> 
>     * a webui to view the scan results in HTML format (probably requires consolidate of results for CRD or similar first)

**Comment by JAORMX** [comment]
@jasinner any way to make that public or give me access?
