### ISSUE TITLE
Tailored profiles, enable rules instead of disable

### ISSUE THREAD

**Issue by zrlvep** [openshift/compliance-operator#628]
Hello people

Is it possible to add the behaviour to tailored profiles to specifically enable rules of a profile in addition to disable? We have the problem that with new versions of the complianceascode image, new rules are introduced automatically and might make our cluster non-compliant. In our operating mode it makes more sense to have a fixed set of rules enabled and assess new rules in a test environment before enabling them on production. 
As a workaround, I specified the image tag v1.xx instead of latest in the profile bundle to make sure I have a fixed set of rules. 

Regards
Pascal

**Comment by JAORMX** [comment]
@zrlvep hey! Thanks for checking out the operator!

That functionality is already there. Here is the CRD reference: https://github.com/openshift/compliance-operator/blob/master/doc/crds.md#the-tailoredprofile-object

under `spec`, we have the `enableRules` which effectively allows you to turn on rules from the data stream.

Or do you mean that the tailored profile should only turn on a specific set of rules? in SCAP it's possible to create profiles from scratch via a tailoring, but we don't have that functionality at the moment in the operator.

**Comment by zrlvep** [comment]
Hi @JAORMX 

As I understand `spec.enableRules` would enable rules which are disabled by default in the pre-made profiles. 

Yes, create a profile from scratch would also solve the issue. Even better would be if I could specify a profile (e.g. rhcos4-moderate) and then selectively enable rules from the profile.

**Comment by connorgorman** [comment]
@JAORMX Was looking into TailoredProfile in order to support them, I wonder if utilizing something like a disableRules: - * would have the desired effect where we could evaluate disableRules first then potentially add results back via enable?

**Comment by JAORMX** [comment]
@connorgorman that actually makes sense and it sounds fairly easy to rationalize too

**Comment by zrlvep** [comment]
That sounds like a good plan, +1!

**Comment by JAORMX** [comment]
I started looking into an alternative approach, and instead will enable creating profiles from scratch: https://github.com/openshift/compliance-operator/pull/691
