### ISSUE TITLE
Compliance cannot run on OpenSift Container Storage

### ISSUE THREAD

**Issue by siwyroot** [openshift/compliance-operator#642]
Hello,

Compliance Operator fails to finish due to problem with mounting PVC. Works fine with default "thin" class but not with Container Storage PVC ocs-storagecluster-cephfs (check different access) also could not get it work with block storage class ocs-storagecluster-ceph-rbd. Other pods mount PVC from both storage classes without any problem.

OpenShift: 4.6.21 UPI on vmware
Compliance Operator: 0.1.32
Container Storage: 4.6.4

Affected pods:
ocp4-e8-rs-5cd57c5959-wgjcl
rhcos4-mss-master-rs-76459ddcf-wnxq6
rhcos4-mss-worker-rs-79dbb9b8cf-hf26j

Error in events of affected pods:
MountVolume.MountDevice failed for volume "pvc-04cce714-b99e-439f-b593-de260050e5b9" : kubernetes.io/csi: attacher.MountDevice failed to create newCsiDriverClient: driver name openshift-storage.cephfs.csi.ceph.com not found in the list of registered CSI drivers

**Comment by siwyroot** [comment]
Problem is that listed above pods are scheduled on master nodes and OpenShift Container Storage is installed without toleration need to run on masters that's why I get this error. So question is should this run on master nodes or OpenShift Container Storage documentation should be updated to include that tollearion so storage could be attached to master nodes when compliance operator schedules pods on master?

**Comment by JAORMX** [comment]
The compliance operator's decision to schedule on the master nodes is deliberate. The premise is that worker nodes are inherently untrusted as they could run any workload, while master nodes only run control plane workloads. Hence, to run compliance-related workloads, it makes the most sense to run on master nodes. This has the added benefit that compliance scans won't take customer workload resources. I'd suggest rather adding a toleration so storage can be used on the master nodes.

**Comment by siwyroot** [comment]
> The compliance operator's decision to schedule on the master nodes is deliberate. The premise is that worker nodes are inherently untrusted as they could run any workload, while master nodes only run control plane workloads. Hence, to run compliance-related workloads, it makes the most sense to run on master nodes. This has the added benefit that compliance scans won't take customer workload resources. I'd suggest rather adding a toleration so storage can be used on the master nodes.

Hello,
Thanks for reply, as per OpenShift documentation master nodes should be set to unschedule and container storage follow this but not adding toleration to OCS deployment for master node. I will open case for OCS to update docs as I do not know if I can modify deployment of OCS after.
