### ISSUE TITLE
ComplianceScan object not created when compliance Suite created

### ISSUE THREAD

**Issue by praveenlnx** [openshift/compliance-operator#643]
Hi, 

As per doc - https://docs.openshift.com/container-platform/4.6/security/compliance_operator/compliance-scans.html
using scansettingbinding, we're trying to create cis-compliance scan. this one creates the compliance suite, but it doesn't create the ComplianceScan to scanning all the profiles which imported through ScansettingBinding.

$ oc get scansettingbinding
NAME             AGE
cis-compliance   24m

$ oc get compliancesuite
NAME             PHASE   RESULT
cis-compliance

$ oc get compliancescan
No resources found in openshift-compliance namespace.

------
apiVersion: compliance.openshift.io/v1alpha1
kind: ScanSettingBinding
metadata:
  name: cis-compliance
profiles:
  - name: ocp4-cis-node
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
  - name: ocp4-cis
    kind: Profile
    apiGroup: compliance.openshift.io/v1alpha1
settingsRef:
  name: default
  kind: ScanSetting
  apiGroup: compliance.openshift.io/v1alpha1

--------

Error Logs:
{"level":"info","ts":1621338016.6643226,"logger":"scansettingbindingctrl","msg":"Suite does not need update","Request.Namespace":"openshift-compliance","Request.Name":"cis-compliance","suite.Name":"cis-compliance"}
{"level":"info","ts":1621338026.2168467,"logger":"suitectrl","msg":"Reconciling ComplianceSuite","Request.Namespace":"openshift-compliance","Request.Name":"cis-compliance"}
{"level":"error","ts":1621338026.2235043,"logger":"controller","msg":"Reconciler error","controller":"compliancesuite-controller","name":"cis-compliance","namespace":"openshift-compliance","error":"Error setting initial status for suite: ComplianceSuite.compliance.openshift.io \"cis-compliance\" is invalid: status.scanStatuses: Required value","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/remote-source/deps/gomod/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/remote-source/deps/gomod/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.2/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.5/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.5/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.5/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/remote-source/deps/gomod/pkg/mod/k8s.io/apimachinery@v0.19.5/pkg/util/wait/wait.go:90"}

**Comment by JAORMX** [comment]
@praveenlnx what OCP version and what operator version is this in?

**Comment by praveenlnx** [comment]
$ oc get clusterversion
NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.7.8     True        False         8d      Cluster version is 4.7.8

NAME                                             DISPLAY                          VERSION   REPLACES                     PHASE
compliance-operator.v0.1.32   Compliance Operator              0.1.32                                 Succeeded

**Comment by JAORMX** [comment]
@praveenlnx sorry that it took me a long time to get back to this. It's been quite hectic. Are you still experiencing this issue? This is a common scenario that we test often, so I find this quite weird. Was this installed via the OLM?
