### ISSUE TITLE
RFE: The mapping for remediation's to machine config pools maybe overly restrictive and hard to understand.

### ISSUE THREAD

**Issue by bnwhorton** [openshift/compliance-operator#671]
Been working to apply remediation to a custom machine config pool to smoke test the changes before rolling them out to the rest of the cluster. From my understanding of how the function works

https://github.com/openshift/compliance-operator/blob/3df4b4116f5e891af3c1499d8d55cc62854db45a/pkg/controller/complianceremediation/complianceremediation_controller.go#L455

You need to have the machine config pool node selector mirror the node selector in the scan AND have the first role on the node match the machine config role labels. 

Would it be better to limit the requirements to 1 of these and let the role mapping to function on a match all roles?

**Comment by JAORMX** [comment]
@bnwhorton that's a good point... I was afraid someone was gonna bump into this. Mind adding a little bit more concrete example of what you're encountering? We initially tried to use the node roles as those are standard in kube, and encouraged. But if that is too restrictive, we'd need to revisit that whole approach.

**Comment by bnwhorton** [comment]
So in our case we where deploying worker nodes with added stig configurations. We wanted to smoke test the stigs on a subset of nodes before we rolled the configs to the entire cluster aka "stigpreview" and "worker" labeled nodes. Right now we where able to move forward with one label, however as we where running the draft stigs there will likely be use cases where we would like to stig preview workers separately from master nodes and other configs. 

I wouldnt say this is any form of blocker but a nice to have. More urgently if it could be added to the docs that would help, I maybe able to submit a PR for review on the docs if that would help.
