### ISSUE TITLE
The deploy/eks.yaml file adds conflicting deployments to the OLM CSV file during a release

### ISSUE THREAD

**Issue by rhmdnd** [openshift/compliance-operator#781]
If you make a release, the operator-sdk will pickup a recently added deployment (deploy/eks.yaml) and incorporate that deployment into the CSV for the release.

This isn't intended since OLM is an OpenShift-specific concept, and the eks.yaml deployment file is meant for running the operator on AWS EKS.

We should find a way to work around this so that we don't accidentally add a deployment to the OLM CSV when it will break on OpenShift deployments.

**Comment by Vincent056** [comment]
The issue was also present when running `make deploy-local`

**Comment by felixkrohn** [comment]
When doing a fresh installation of compliance-operator v0.1.48 on ocp4.8 through operatorhub, I still get two competing deployments in the CSV, leading to high cluster load and a broken operator installation.
Could you release a new version without the EKS yaml?

**Comment by rhmdnd** [comment]
I'm curious how you installed. Here is what I have with a fresh deployment using v0.1.48:

```
 $ oc get csv -n openshift-compliance
NAME                          DISPLAY               VERSION   REPLACES   PHASE
compliance-operator.v0.1.48   Compliance Operator   0.1.48               Succeeded
```

But, I only see a single deployment in the CSV.

```
$ oc get csv -n openshift-compliance -o json | jq '.items[0].spec.install.spec.deployments'
[
  {
    "name": "compliance-operator",
    "spec": {
      "replicas": 1,
      "selector": {
        "matchLabels": {
          "name": "compliance-operator"
        }
      },
      "strategy": {},
      "template": {
        "metadata": {
          "annotations": {
            "workload.openshift.io/management": "{\"effect\": \"PreferredDuringScheduling\"}"
          },
          "creationTimestamp": null,
          "labels": {
            "name": "compliance-operator"
          }
        },
        "spec": {
          "containers": [...],
          "nodeSelector": {
            "node-role.kubernetes.io/master": ""
          },
          "serviceAccountName": "compliance-operator",
          "tolerations": [
            {
              "effect": "NoSchedule",
              "key": "node-role.kubernetes.io/master",
              "operator": "Exists"
            }
          ],
          "volumes": [
            {
              "name": "serving-cert",
              "secret": {
                "optional": true,
                "secretName": "compliance-operator-serving-cert"
              }
            }
          ]
        }
      }
    }
  }
]
```

Is that different from what you have?

**Comment by felixkrohn** [comment]
@rhmdnd I install by creating a set of objects (namespace "openshift-compliance", catalogsource in openshift-marketplace, subscription, operatorgroup, role, rolebinding) via argoCD.
This renders a CSV with two deployments:
```
$ oc get csv compliance-operator.v0.1.48 compliance-operator.v0.1.48 -n openshift-compliance -o json | jq '.items[0].spec.install.spec.deployments[].spec.template.spec.containers[0].image'
"quay.io/compliance-operator/compliance-operator:latest"
"quay.io/compliance-operator/compliance-operator:0.1.48"
$ oc get csv compliance-operator.v0.1.48 compliance-operator.v0.1.48 -n openshift-compliance -o json | jq '.items[0].spec.install.spec.deployments[].spec.template.spec.containers[0].command'
[
  "compliance-operator",
  "operator",
  "--platform",
  "eks"
]
[
  "compliance-operator",
  "operator"
]
```
I was able to reproduce this right now.

**Comment by felixkrohn** [comment]
ok, seems unnecessary nowadays to add a distinct catalogsource (quay.io/compliance-operator/compliance-operator-index:latest); when using the default "redhat-operators" catalogsource there indeed is only one single deployment rendered in the csv.

**Comment by rhmdnd** [comment]
@felixkrohn sounds like you were able to work around the issue?

**Comment by felixkrohn** [comment]
@rhmdnd yup, looks like I used an catalogsource that is not needed/updated anymore. all good for me.
