### ISSUE TITLE
operator-sdk is affecting the build process and tagging

### ISSUE THREAD

**Issue by rhmdnd** [openshift/compliance-operator#783]
We use `make` to carry out our build process, which contains steps that use operator-sdk to update CRDs in the compliance-operator.

During the build process the operator-sdk is removing the `statusDescriptor` portions of the generated CSV. This is because we're not annotating the `statusDescriptor` objects appropriately in the source.

This issue is compounded at release time when the `make release` target builds the updated CSV with the `statusDescriptors` removed, commits the change, and then tags it before pushing the change. We have to go back and re-add `statusDescriptors` to the commit, causing the tag during the release process to differ from the commit with the correct CSV.

You can determine this by looking at tag 0.1.47:

```
$ git show -s v0.1.47                                                                                                                                                                                          commit d1afdfe23cc29ac85c810d82abe6c309cdecd6d3 (tag: v0.1.47, upstream/release-v0.1.47)
Author: Jakub Hrozek <jhrozek@redhat.com>
Date:   Wed Dec 15 17:37:08 2021 +0100
    Release v0.1.47
$ git branch --contains d1afdfe23cc29ac85c810d82abe6c309cdecd6d3
$
```

This will affect people who are checking out releases based on tags and potentially break them.

**Comment by rhmdnd** [comment]
One potential way we could fix this would be to decouple the operator-sdk update from the git operations in the `release` target.

Right now everything is done when a maintainer performs `make release`. If we break that into:

```
$ make prepare-release
$ make release
```

We could give ourselves the opportunity to inspect the release changes to OLM objects, CRDs, and helm charts before building the commit and tagging it.

Thoughts? Or should we consider invoking it differently with operator-sdk?

**Comment by Vincent056** [comment]
I think we can add an extra step after operator-sdk overwrite the csv, save the `statusDescriptor` as patch, apply the patch after operator-sdk generate as a temp solution.

**Comment by rhmdnd** [comment]
@Vincent056 Ok, so you'd prefer a two-step solution where the maintainer (whoever is cutting the release) runs `prepare-release` then `release`?

Applying a temp patch for the `statusDescriptor` will get us around one problem we had, but we also needed to remove the extra deployment from the CSV. I'm in favor of a two-step process, unless maintainers want to keep a single command for the release.

**Comment by Vincent056** [comment]
I think the two-step solution will be much better

**Comment by Vincent056** [comment]
> @Vincent056 Ok, so you'd prefer a two-step solution where the maintainer (whoever is cutting the release) runs `prepare-release` then `release`?
> 
> Applying a temp patch for the `statusDescriptor` will get us around one problem we had, but we also needed to remove the extra deployment from the CSV. I'm in favor of a two-step process, unless maintainers want to keep a single command for the release.

I think the two-step solution will be much better
