### ISSUE TITLE
Broken link to self-paced workshop (doc issue)

### ISSUE THREAD

**Issue by AdrianHammond** [openshift/compliance-operator#807]
The link to the self paced workshop in the usage guide (https://github.com/openshift/compliance-operator/blob/master/doc/usage.md) is broken. The self paced workshop link takes you to https://github.com/openshift/compliance-operator/blob/master/doc/doc/tutorials/README.md which give a 404 error, I used https://github.com/openshift/compliance-operator/blob/master/doc/tutorials/README.md (removed duplicate /doc) which works.

**Comment by AdrianHammond** [comment]
I opened a PR - here is link https://github.com/openshift/compliance-operator/pull/808

My first.....  Really enjoyed the tutorial. Will follow up via email with you.

**Comment by rhmdnd** [comment]
Closing this since https://github.com/openshift/compliance-operator/pull/808 merged.
