### ISSUE TITLE
Please do not open issues against this repository

### ISSUE THREAD

**Issue by rhmdnd** [openshift/compliance-operator#826]
This repository was forked to https://github.com/ComplianceAsCode/compliance-operator and is no longer accepting new PRs or issues.

Please open relevant issues against https://github.com/ComplianceAsCode/compliance-operator instead.

**Comment by bortek** [comment]
Does this mean that Redhats operator in the operator hub will use the new forked repo or will it still this "old" one?

In which repo should we expect to have latest updated documentation , this or that one ?

**Comment by JAORMX** [comment]
@bortek The change won't affect Red Hat's OperatorHub installation; as a matter of fact, as a user you shouldn't see a difference. The main thing is where upstream development happens. Eventually, this repository will become a mirror of upstream.
