### ISSUE TITLE
Compliance operator scans may leave namespaces stuck terminating

### ISSUE THREAD

**Issue by rtheis** [openshift/compliance-operator#831]
The Red Hat OpenShift on IBM Cloud test pipeline uses the compliance operator for compliance scanning. Most of the time, this testing goes smoothly. However, there are times when there are general compliance operator scan problems that leave `profilebundle` and/or `compliancescan` resources behind.  These resources have a Kubernetes finalizer that is not cleared and thus namespace termination is blocked.  We have tried to order compliance operator cleanup but the problem keeps occurring.

**Comment by jhrozek** [comment]
I'm afraid I don't have a great solution except prune the profile bundles manually. The order in which I'd do that would be:
```
oc delete ssb --all -n$namespace
# in case you're using raw suites/scans for some reason
oc delete suites --all -n$namespace
oc delete scans --all -n$namespace
oc delete pb.compliance --all -n$namespace
```

**Comment by jhrozek** [comment]
maybe we should document this more prominently?

**Comment by jhrozek** [comment]
btw this repository is a fork of upstream which lives at https://github.com/ComplianceAsCode/compliance-operator/ it's preferred to open issues there (mostly because more people look there).

**Comment by rtheis** [comment]
Thanks, I've transferred the issue to https://github.com/ComplianceAsCode/compliance-operator/issues/56.
