### ISSUE TITLE
Creating multiple compliancesuite CRs doesn't trigger a scan

### ISSUE THREAD

**Issue by nkinder** [openshift/compliance-operator#84]
If you trigger a scan by creating a compliancesuite CR, but leave it around, it prevents further scans from running with you create another compliancesuite CR.  It seems that this is caused by the pod names already existing for each node.

If you delete the original compliancescan CR first, it will then work as expected when you attempt to run another scan.  We should allow multiple scans to run, as keeping the results of previous scans for historical purposes may be desired.

**Comment by JAORMX** [comment]
this work was a lot more involved than I thought. Deferring for later.
